### ISSUE TITLE
encoder failed on samsung devices

### ISSUE THREAD

**Issue by vaibhavkvh** [1612052/Zecorder#12]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2127)
        at android.media.MediaCodec.configure(MediaCodec.java:2043)
        at com.screenrecorder.foregroundservice.encoder.MediaVideoEncoderBase.prepare_surface_encoder(MediaVideoEncoderBase.java:93)
        at com.screenrecorder.foregroundservice.encoder.MediaScreenEncoderHard.prepare(MediaScreenEncoderHard.java:64)
        at com.screenrecorder.foregroundservice.encoder.MediaMuxerWrapper.prepare(MediaMuxerWrapper.java:82)
        at com.screenrecorder.foregroundservice.recording.RecordingService.startRecording(RecordingService.java:165)
        at com.screenrecorder.foregroundservice.recording.RecordingService.startPerformService(RecordingService.java:109)
        at com.screenrecorder.foregroundservice.ControllerService$4$1.onFinish(ControllerService.java:316)
        at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:127)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by pancumtneu** [comment]
I have the similar error On Oppo device whose OS is Android 12:

W/ColorUtils: expected specified color aspects (0:0:255:255)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.chienpm.zecorder, PID: 27156
    java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2176)
        at android.media.MediaCodec.configure(MediaCodec.java:2092)
        at com.chienpm.zecorder.controllers.encoder.MediaVideoEncoderBase.prepare_surface_encoder(MediaVideoEncoderBase.java:93)
        at com.chienpm.zecorder.controllers.encoder.MediaScreenEncoderHard.prepare(MediaScreenEncoderHard.java:66)
        at com.chienpm.zecorder.controllers.encoder.MediaMuxerWrapper.prepare(MediaMuxerWrapper.java:81)
        at com.chienpm.zecorder.ui.services.recording.RecordingService.startRecording(RecordingService.java:167)
        at com.chienpm.zecorder.ui.services.recording.RecordingService.startPerformService(RecordingService.java:111)
        at com.chienpm.zecorder.ui.services.ControllerService$5$1.onFinish(ControllerService.java:469)
        at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:142)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:344)
        at android.app.ActivityThread.main(ActivityThread.java:8212)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
